analyzer:
  errors:
    non_constant_identifier_names: ignore
    constant_identifier_names: ignore
    
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    use_build_context_synchronously: true
